### ISSUE TITLE
Code is empty

### ISSUE THREAD

**Issue by litamin** [iw4rr10r/esp32-ota-web-updates#1]
Hi, I see you've spent a lot of time on this and we all appreciate it, but where's the actual code? :)

**Comment by m1cr0lab** [comment]
Hi, and thanks for your interest!

The code is **not** empty 😂 

The main sketch is located at the root of the repository: [ota-web-updates.ino](https://github.com/iw4rr10r/esp32-ota-web-updates/blob/master/ota-web-updates.ino).
Depending on the application you want to compile, you must then uncomment the corresponding line :

```cpp
// #include "src/bme280.h"
// #include "src/led.h"
```

The C++ code for each of these applications can be found in the [src](https://github.com/iw4rr10r/esp32-ota-web-updates/tree/master/src) folder.
And the user interface code for each web application (HTML/CSS/JavaScript) can be found in the [data](https://github.com/iw4rr10r/esp32-ota-web-updates/tree/master/data) folder.  So you need to copy the contents of this folder on the ESP32's SPIFFS file system.

However, it is all explained in the [Readme](https://github.com/iw4rr10r/esp32-ota-web-updates) of the repository. But in order to fully understand what we are doing here, I assume that you have already carefully read Rui & Sara tutorials recommended in the Readme.

**Comment by litamin** [comment]
Ah haha understood! I have used Rui & Sara's Webserver and OTA tutorials, but there are two different Webserver ones; one without and one with SPIFFS. I have so far only used the one without SPIFFS (https://randomnerdtutorials.com/esp32-web-server-arduino-ide/). Can you explain the difference and the pros/cons of them?

Btw, if you aim to share code for using webserver+OTA, it would really help noobs like me if other stuff like leds/sensors and options between them and whatnot was _not_ included in this code. It just makes things messier. Just a thought - thank you nevertheless!

**Comment by m1cr0lab** [comment]
Choosing to host the resource files that make up the web user interface of each application on the SPIFFS file system simply makes the C++ code running on the microcontroller much lighter. It therefore increases the general readability of the code.

It also makes it possible to host these same user interface files in the ESP32 Flash memory without the risk of unnecessarily occupying RAM during the execution of C++ code.

Finally, to illustrate the process of performing an OTA web update from two separate applications, it seemed to me that it would be much clearer to present two simple and completely independent applications, each of which integrates the communication routines needed for the OTA web update. The points specifically related to the LEDs or the weather sensor are sufficiently succinct so as not to hinder the overall understanding of the general update process and exchanges with the web server.

Unfortunately, I didn't have time to write a complete tutorial on my whole approach, but it seems to me that the preliminary reading of Rui and Sara's tutorials that I recommended makes the global understanding of the integration of the different modules much easier to apprehend at the same time. It seems important to me to have made the effort to study these tutorials well in the first place. Reading my code, then, makes it possible to understand the articulation of its various components.

I would also like to specify that my initiative is a detailed answer to one of the readers of the RNTLab forum (David H.). I have therefore precisely targeted the elements that were causing him difficulty. I then considered that it could be of interest to other readers, and that is why I shared my code.

I'm sorry if it doesn't meet your expectations as it stands... but I have obligations in real life that don't always allow me to devote the time I would like to help others. I do what I can, when I can, as I can.
